### ISSUE TITLE
Spaces replaced with _

### ISSUE THREAD

**Issue by AndrewBotalov80** [Flagsmith/flagsmith-flutter-client#13]
StateValue text replace spaces with "_" after reading fetched flags.

Steps:
1. Create flags
2. Fetch flags (everything is good at console)
<img width="1249" alt="Снимок экрана 2021-09-04 в 12 11 05" src="https://user-images.githubusercontent.com/18752756/132086364-8f47a705-3088-4939-b9b8-cbd459ff2d19.png">
3. Try to read value with client.getFeatureFlagValue(key)
<img width="719" alt="Снимок экрана 2021-09-04 в 12 13 43" src="https://user-images.githubusercontent.com/18752756/132086230-2e3067c6-5ced-48a3-9151-c9c1403ad0b4.png">
4. Result
<img width="761" alt="Снимок экрана 2021-09-04 в 12 16 05" src="https://user-images.githubusercontent.com/18752756/132086313-e2ec0d74-5042-45a7-8a50-deabfdfc2b0d.png">

Also tried to get all feature flags and get stateValue myself.
<img width="713" alt="Снимок экрана 2021-09-04 в 12 25 01" src="https://user-images.githubusercontent.com/18752756/132086547-b5c8a650-65b5-4979-be6c-6db1e91d4b4a.png">
<img width="584" alt="Снимок экрана 2021-09-04 в 12 25 28" src="https://user-images.githubusercontent.com/18752756/132086552-6ea305f3-7e1b-44a3-9fdb-f9f93220dc61.png">

Same result:
<img width="771" alt="Снимок экрана 2021-09-04 в 12 27 55" src="https://user-images.githubusercontent.com/18752756/132086728-a1420f5c-ae91-4bb9-99c6-44604004fccb.png">

Flagsmith config
<img width="657" alt="Снимок экрана 2021-09-04 в 12 20 27" src="https://user-images.githubusercontent.com/18752756/132086461-2bd40323-cbba-4435-9b20-2aa74a0d6335.png">

Configuration:
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.60.0)
[✓] Connected device (2 available)
```
pubspec
```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  after_layout: ^1.1.0
  collection: ^1.15.0
  flagsmith: ^2.0.0-nullsafety.0
  enum_to_string: ^2.0.1
```
